spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    locations: classpath:db/migration
    enabled: true

resrv:
  jwt:
    secret-key: ${RESRV_JWT_SECRET_KEY}
    issuer: ${RESRV_JWT_ISSUER}
    audience: ${RESRV_JWT_AUDIENCE}
    expiration: ${RESRV_JWT_EXPIRATION}
  security:
    password-reset:
      public-base-url: ${RESRV_SECURITY_PASSWORD_RESET_PUBLIC_BASE_URL}
      token-ttl: ${RESRV_SECURITY_PASSWORD_RESET_TOKEN_TTL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: never
      group:
        readiness:
          include: readinessState,db
